function [fitresult, gof] = createFit1(mux1, mux2, muy)
%CREATEFIT1(MUX1,MUX2,MUY)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : mux1
%      Y Input : mux2
%      Z Output: muy
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 03-Feb-2018 23:27:46


%% Fit: 'untitled fit 1'.
[xData, yData, zData] = prepareSurfaceData( mux1, mux2, muy );

% Set up fittype and options.
ft = fittype( 'poly55' );
opts = fitoptions( 'Method', 'LinearLeastSquares' );
opts.Robust = 'LAR';

% Fit model to data.
[fitresult, gof] = fit( [xData, yData], zData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, [xData, yData], zData );
legend( h, 'untitled fit 1', 'muy vs. mux1, mux2', 'Location', 'NorthEast' );
% Label axes
xlabel 'Sensor 1'
ylabel 'Sensor 2'
zlabel 'Y Pos'
grid on
view( 290.9, 21.2 );


